<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;DebugWeb;ReleaseWeb;PublishWin</Configurations>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='PublishWin|AnyCPU'">
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net9.0-windows10.0.19041.0;net9.0-android;net9.0-ios;net9.0-maccatalyst</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugWeb|AnyCPU'">
    <DefineConstants>$(DefineConstants);_WebApp;DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugWeb|x64'">
    <DefineConstants>$(DefineConstants);_WebApp;DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugWeb|x86'">
    <DefineConstants>$(DefineConstants);_WebApp;DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseWeb|AnyCPU'">
    <DefineConstants>$(DefineConstants);_WebApp</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseWeb|x64'">
    <DefineConstants>$(DefineConstants);_WebApp</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseWeb|x86'">
    <DefineConstants>$(DefineConstants);_WebApp</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazorise.Bootstrap5" Version="1.8.1" />
    <PackageReference Include="Blazorise.Components" Version="1.8.1" />
    <PackageReference Include="Blazorise.DataGrid" Version="1.8.1" />
    <PackageReference Include="Blazorise.Generator.Features" Version="1.8.0" />
    <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.8.1" />
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.7" />
    <PackageReference Include="Radzen.Blazor" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CornerkickApp.Controllers\CornerkickApp.Controllers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\Components\UserClubEmblem\" />
    <Folder Include="wwwroot\Content\Uploads\emblems\" />
    <Folder Include="wwwroot\Content\Uploads\portraits\" />
    <Folder Include="wwwroot\mail\" />
  </ItemGroup>

</Project>
